### PR TITLE
Automate publishing of artifacts

### PR DESCRIPTION
**Pull request by nightscape**
You need to additionally follow the steps listed here:
https://github.com/olafurpg/sbt-ci-release
It's been a while since I did this for spark-excel, but in case you have any questions I'll try to help :)

### CODE REVIEW

**Comment by nightscape** [comment]
And maybe that commit here helps as well: https://github.com/crealytics/spark-excel/commit/1dd2d74b15de8cf03257cb290b60bf8def587247

**Comment by nightscape** [comment]
@MrPowers one point where I deviated from the `sbt-ci-release` tutorial is that I created a GPG key (`private-key.pem.enc`) for signing releases for Sonatype.
After creating the key pair as described in the tutorial I exported and encrypted the key like this (the file extension `.pem` might be completely wrong, I'm bad at crypto :wink:):
```
gpg --output private-key.pem --armor --export-secret-key insert.your.email@add.ress
openssl aes-256-cbc -a -pbkdf2 -in private-key.pem -out private-key.pem.enc
```
In the `openssl` command above I think I just used the same `PGP_PASSPHRASE` that was used to create the key pair.

**Comment by MrPowers** [comment]
@nightscape - Thanks, I'm super new at all this key stuff.  Can we do this to getup on the GPG stuff on the CI server? https://github.com/olafurpg/sbt-ci-release/blob/master/.github/workflows/release.yml#L12

I am a little worried about uploading a private key file in source control, even if it's encrypted... thoughts?

Thanks so much for all the help!!

**Comment by nightscape** [comment]
I had a look at the setup-gpg action and it really just installs gpg.
Regarding the private key:
Afaik, you could just generate a fresh one each time you run a build, because Sonatype actually doesn't care about which key you use.
Otoh, the key you're uploading is one that you generate for this single purpose.
There may be other ways to do it, but I couldn't get it to run without this. Things may have changed in the mean time though.

**Comment by MrPowers** [comment]
@nightscape - Thanks to your help, I am now able to publish spark-daria and spark-fast-tests properly in Maven.  Really appreciate your help.

I am going to revisit the automated CI publishing in a couple of months.  I am going to try to learn more about GPG, PGP, and just really understand what's going on here.

Can you send me an email (my email address is in my GitHub profile).  Would like to brainstorm some spark-excel ideas with you!

**Pull request merged**
