### PR TITLE
ignoreNullable on complex Spark data types

### LINKED ISSUE #96: bug: ignoreNullable doesn't work for nested StructTypes
For test case:

```
  test("test dataFrameComparer") {
    val df1 = spark.createDataFrame(
      spark.sparkContext.emptyRDD[Row],
      StructType(
        List(
          StructField("nested_struct",
            StructType(
              List(
                StructField("field", StringType, true),
              )
            )
          )
        )
      )
    )

    val df2 = spark.createDataFrame(
      spark.sparkContext.emptyRDD[Row],
      StructType(
        List(
          StructField("nested_struct",
            StructType(
              List(
                StructField("field", StringType, false),
              )
            )
          )
        )
      )
    )

    assertSmallDataFrameEquality(df1, df2, ignoreNullable=true)
}
```

Expected behavior with `ignoreNullable = true` should be a passed test. Instead, the test fails. This only seems to affect nested fields in StructType columns.

### PR DESCRIPTION
**Pull request by Dressingoak**
This is a problem we have had for quite a while, it didn't seem that hard to fix. Let me know if it makes the comparison too complex. I believe it will fix #96.

### CODE REVIEW

**Comment by MrPowers** [comment]
Thanks for the PR.  I'm open to this.  I don't work with Spark anymore - you know anyone else that can help with a code review.  Here's what's most important to me:

* 100% backwards compatible
* Doesn't slow down tests

Perhaps we can ping some of the other project contributors and see if they're willing to help out with a code review.

**Comment by Dressingoak** [comment]
Thank you. Looking through recent committers, maybe you @skestle or @alfonsorr have a moment to take a look?

**Comment by alfonsorr** [comment]
LGTM, but I don't have the privilege to approve it sorry.
@MrPowers can you change it?

**Comment by jendap** [comment]
LGTM. Fix the problem for us too.

@MrPowers can wyou merge it please?

**Comment by leleogere** [comment]
Are you planning to merge this soon?

**Pull request merged**
